#define PROJ_SCREENMODE TASMODE
#define PROJ_FPS 255
#define PROJ_HIGH_RAM HIGH_RAM_ON
#define PROJ_ENABLE_SOUND 0
//#define PROJ_LINE_FILLERS TAS::NOPFiller, TAS::NOPFiller, TAS::NOPFiller
#define PROJ_MAX_SPRITES 255
